// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VictimsHelp.DAL;

namespace VictimsHelp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210524101449_AddMessageEntity")]
    partial class AddMessageEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VictimsHelp.DAL.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ab5e3ec-ba2e-44a3-96fb-541d53ba159b"),
                            IsDeleted = false,
                            Text = "Domestic violence is a global issue reaching across national boundaries as well as socio-economic, cultural, racial and class distinctions. This problem is not only widely dispersed geographically, but its incidence is also extensive, making it a typical and accepted behavior. Domestic violence is wide spread, deeply ingrained and has serious impacts on women's health and well-being. Its continued existence is morally indefensible. Its cost to individuals, to health systems and to society is enormous. Yet no other major problem of public health has been so widely ignored and so little understood.",
                            Title = "Addressing Domestic Violence Against Women: An Unfinished Agenda"
                        },
                        new
                        {
                            Id = new Guid("9ac64c34-d62d-40ce-babc-161654a03756"),
                            IsDeleted = false,
                            Text = "Domestic violence can be described as the power misused by one adult in a relationship to control another. It is the establishment of control and fear in a relationship through violence and other forms of abuse. This violence can take the form of physical assault, psychological abuse, social abuse, financial abuse, or sexual assault. The frequency of the violence can be on and off, occasional or chronic.",
                            Title = "What is Domestic Violence?"
                        });
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64a967c4-0caf-4e34-9697-fcd428629916"),
                            IsDeleted = false,
                            Name = "Client"
                        },
                        new
                        {
                            Id = new Guid("3c1c8a71-9110-4258-858b-ed5d6855fd38"),
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("500baaa9-3826-4c82-aa06-c1b827676bd3"),
                            IsDeleted = false,
                            Name = "Psychologist"
                        });
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PsychologistEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PsychologistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7979a3c-2e0d-40b5-ad52-ca21469336f3"),
                            Age = 25,
                            Email = "admin1@gmail.com",
                            FirstName = "admin1",
                            Gender = "M",
                            IsDeleted = false,
                            LastName = "admin1",
                            Password = "$2a$11$A1.DAG8c68avBpLs3MgAwefKw.HBhV5NksdXLshxgnAHaoxEGpgy.",
                            PhoneNumber = "0501234567"
                        },
                        new
                        {
                            Id = new Guid("8d703abc-cde4-4338-8dae-6c30f1d9efd9"),
                            Age = 20,
                            Email = "user1@gmail.com",
                            FirstName = "User1",
                            Gender = "W",
                            IsDeleted = false,
                            LastName = "User1",
                            Password = "$2a$11$5VYh3St65BRLBwRCYrVEie0FNylQ7Uvb.WjEM13WOh/KXyh.rSOqC",
                            PhoneNumber = "0998887766",
                            PsychologistEmail = "user2@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("dd2a504d-a40b-407e-b5e4-c15dea155dd9"),
                            Age = 25,
                            Email = "user2@gmail.com",
                            FirstName = "Psychologist",
                            Gender = "M",
                            IsDeleted = false,
                            LastName = "Psychologist",
                            Password = "$2a$11$k0qrKDsOOobvmvSCgVbFAuxuI2GDGc0fX32c3KuZ7DHZrcGIAKpku",
                            PhoneNumber = "0501234567"
                        });
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f17f0e8-7c1a-4edb-ba04-fd0342107616"),
                            IsDeleted = false,
                            RoleId = new Guid("64a967c4-0caf-4e34-9697-fcd428629916"),
                            UserId = new Guid("8d703abc-cde4-4338-8dae-6c30f1d9efd9")
                        },
                        new
                        {
                            Id = new Guid("be9eee3b-7a25-4d3f-827b-eb44d86b72db"),
                            IsDeleted = false,
                            RoleId = new Guid("3c1c8a71-9110-4258-858b-ed5d6855fd38"),
                            UserId = new Guid("a7979a3c-2e0d-40b5-ad52-ca21469336f3")
                        },
                        new
                        {
                            Id = new Guid("0e2569f8-ebac-4587-9cc2-ec814e278aee"),
                            IsDeleted = false,
                            RoleId = new Guid("500baaa9-3826-4c82-aa06-c1b827676bd3"),
                            UserId = new Guid("a7979a3c-2e0d-40b5-ad52-ca21469336f3")
                        },
                        new
                        {
                            Id = new Guid("e7b6e5c6-f601-4e82-8dab-55476e31b153"),
                            IsDeleted = false,
                            RoleId = new Guid("64a967c4-0caf-4e34-9697-fcd428629916"),
                            UserId = new Guid("a7979a3c-2e0d-40b5-ad52-ca21469336f3")
                        },
                        new
                        {
                            Id = new Guid("f4fb3d5c-ce85-4bdb-a233-c58ac165ee5b"),
                            IsDeleted = false,
                            RoleId = new Guid("500baaa9-3826-4c82-aa06-c1b827676bd3"),
                            UserId = new Guid("dd2a504d-a40b-407e-b5e4-c15dea155dd9")
                        });
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.Message", b =>
                {
                    b.HasOne("VictimsHelp.DAL.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("VictimsHelp.DAL.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.User", b =>
                {
                    b.HasOne("VictimsHelp.DAL.Entities.User", "Psychologist")
                        .WithMany("Clients")
                        .HasForeignKey("PsychologistId");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.UserRole", b =>
                {
                    b.HasOne("VictimsHelp.DAL.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VictimsHelp.DAL.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VictimsHelp.DAL.Entities.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Messages");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
